### ISSUE TITLE
Factor analysis step caching into separate package

### ISSUE THREAD

**Issue by ghing** [wireservice/proof#12]
I like the idea behind proof, but find the step chaining cumbersome in some cases.  I know this isn't very constructive feedback and I'm still working out exactly which cases these are.  Rather than feature requesting and making the tool more opinionated about workflow, I'm wondering if the caching logic/API could be factored out into a separate package, allowing the persisting of data and passing it between steps to work using a different task runner, such as invoke.

Factoring this out into a separate package could also parameterize this operation, one day allowing power users to address #11 by serializing to a different format assuming their data is easily serialized as JSON (or something else).

**Comment by onyxfish** [comment]
Hmm, I don't have a clear idea of what you have in mind here. I have also sometimes found the chaining to be cumbersome, though my gut says that is going to be true of any procedural workflow. A declarative syntax like [flo](http://flo.readthedocs.org/en/latest/) uses is somewhat tidier, though at the cost of being more verbose for simple workflows.

I'd rather not over-specify proof if there isn't a particular goal in mind. I think it's niche is the quick-and-dirty one-file workflows. There are a lot of task runners out there for doing more elaborate processing. Happy to hear dissenting opinions, of course, but don't want to split it up unless a compelling case has been documented.

**Comment by jpmckinney** [comment]
Not sure that there's a specific request, so closing.
