### ISSUE TITLE
Make it possible to retrieve the final data object from an executed analysis

### ISSUE THREAD

**Issue by aplayford** [wireservice/proof#16]
This would make it easier to use Proof to load and clean your data, then to switch to exploratory analysis with another tool, such as a Jupyter notebook.

**Comment by onyxfish** [comment]
Hey, not sure I understand what prevents you from doing this now. Can't you just put a ```table.to_csv('foo.csv')``` in the final step of your process?

**Comment by onyxfish** [comment]
That example was agate specific, but more generally you can write whatever output step you like into your process.
