### ISSUE TITLE
A built-in way to define a process as the last one to be executed

### ISSUE THREAD

**Issue by alexandre** [wireservice/proof#17]
Hello,

Would be great if there was a built-in way to define that a process will be the last one executed. Something like:
## works as expected...

``` python

analysis = proof.Analysis(initialize_data, last_process=last_process)
analysis.then(process_0)
analysis.then(process_1)
analysis.then(process_2)
analysis.then(last_process)
```
## raises an exception

``` python

analysis = proof.Analysis(initialize_data, last_process=last_process)
analysis.then(process_0)
analysis.then(process_1)
analysis.then(process_2)
analysis.then(last_process)
analysis.then(process_3)
# Exception(Other process was added after the one specified as the last one.)
```
## raises an exception

``` python

analysis = proof.Analysis(initialize_data, last_process=last_process)
analysis.then(process_0)
analysis.then(process_1)
analysis.then(process_2)
# Exception(It's missing the last one!)
```

In the last example, instead an exception, the call of the method `then` (with the last process) could be implicit, but you know... _"Explicit is better than implicit."_

What do you think ?

**Comment by jpmckinney** [comment]
I'm not clear on why providing the last step in the first line is preferred over leaving it where it is, as a final `then`.

I'm also not sure why a user would want to enforce a contract that a step labelled "last" is truly the last step.
