### ISSUE TITLE
Branching architecture?

### ISSUE THREAD

**Issue by frnsys** [wireservice/proof#6]
In `broca` there's support for [branching pipelines](https://github.com/ftzeng/broca#multi-pipelines) so you can combine pipelines which have many redundant components - I was thinking of breaking that out into a separate package but it seems like it may be appropriate for `proof` - what do you think?

**Comment by onyxfish** [comment]
I considered this as a feauture for proof but couldn't decide how to model it. If there is a way we could hack this so it could implement the pattern you need to make it part of broca I'm all for that. So as long as it doesn't make the API overly complex for users who want the current pattern.

**Comment by onyxfish** [comment]
Upon rereading this, I'm pretty sure proof already supports what you want. You can already have a multiple children of a single parent analysis. What you can't have is a single child with multiple parents. It's a descent-only hierarchy.
